=== devdanielmoreno/XML/XML/XSD/Eje6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="persones">
<xs:complexType>
<xs:sequence maxOccurs="unbounded">
<xs:element ref="usuaris"/>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="usuaris">
<xs:complexType>
<xs:sequence maxOccurs="2">
<xs:element ref="usuari"/>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="usuari">
<xs:complexType>
<xs:sequence maxOccurs="1">
<xs:element ref="nom"/>
<xs:element ref="contrasenya"/>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="nom" type="xs:string"/>
<xs:element name="contrasenya">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute name="num" use="optional">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value="[A-Z][0-9]+" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>
</xs:schema>

=== devdanielmoreno/XML/XML/XSD/Eje6.xml
<?xml version="1.0" encoding="UTF-8"?>
<persones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Eje6.xsd">
<usuaris>
<usuari>
<nom>juliams</nom>
<contrasenya>Kj895S</contrasenya>
</usuari>
<usuari>
<nom>carles3</nom>
<contrasenya>123456</contrasenya>
</usuari>
</usuaris>
</persones>
